name: Copy TVBox Source

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Source
        run: |
          URL=$(cat my_source.txt)
          curl -L "$URL" -o my_TVBox.json

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add my_TVBox.json

          if ! git diff --cached --quiet; then
            git commit -m "Update TVBox source"
            git push
          fi
